/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AlertVariant } from "./components/fb-alert/fb-alert";
import { BadgeSize, BadgeVariant } from "./components/fb-badge/fb-badge";
import { BreadcrumbItem } from "./components/fb-breadcrumb/fb-breadcrumb";
import { ButtonSize, ButtonVariant, IconPosition } from "./components/fb-button/fb-button";
import { GroupOrientation } from "./components/fb-button-group/fb-button-group";
import { CheckboxSize, CheckboxState } from "./components/fb-checkbox/fb-checkbox";
import { DropdownItem } from "./components/fb-dropdown/fb-dropdown";
import { InputSize, InputState, InputType } from "./components/fb-input/fb-input";
import { ModalSize } from "./components/fb-modal/fb-modal";
import { RadioOption } from "./components/fb-radio-group/fb-radio-group";
import { SelectOption, SelectSize, SelectState } from "./components/fb-select/fb-select";
import { SidebarItem } from "./components/fb-sidebar/fb-sidebar";
import { SkeletonVariant } from "./components/fb-skeleton/fb-skeleton";
import { SpinnerSize } from "./components/fb-spinner/fb-spinner";
import { TabItem, TabsSize, TabsVariant } from "./components/fb-tabs/fb-tabs";
import { TextareaSize, TextareaState } from "./components/fb-textarea/fb-textarea";
import { TimelineItem } from "./components/fb-timeline/fb-timeline";
import { ToastVariant } from "./components/fb-toast/fb-toast";
import { ToggleSize, ToggleVariant } from "./components/fb-toggle/fb-toggle";
import { ToggleGroupOrientation, ToggleGroupSize, ToggleGroupType, ToggleGroupVariant } from "./components/fb-toggle-group/fb-toggle-group";
export { AlertVariant } from "./components/fb-alert/fb-alert";
export { BadgeSize, BadgeVariant } from "./components/fb-badge/fb-badge";
export { BreadcrumbItem } from "./components/fb-breadcrumb/fb-breadcrumb";
export { ButtonSize, ButtonVariant, IconPosition } from "./components/fb-button/fb-button";
export { GroupOrientation } from "./components/fb-button-group/fb-button-group";
export { CheckboxSize, CheckboxState } from "./components/fb-checkbox/fb-checkbox";
export { DropdownItem } from "./components/fb-dropdown/fb-dropdown";
export { InputSize, InputState, InputType } from "./components/fb-input/fb-input";
export { ModalSize } from "./components/fb-modal/fb-modal";
export { RadioOption } from "./components/fb-radio-group/fb-radio-group";
export { SelectOption, SelectSize, SelectState } from "./components/fb-select/fb-select";
export { SidebarItem } from "./components/fb-sidebar/fb-sidebar";
export { SkeletonVariant } from "./components/fb-skeleton/fb-skeleton";
export { SpinnerSize } from "./components/fb-spinner/fb-spinner";
export { TabItem, TabsSize, TabsVariant } from "./components/fb-tabs/fb-tabs";
export { TextareaSize, TextareaState } from "./components/fb-textarea/fb-textarea";
export { TimelineItem } from "./components/fb-timeline/fb-timeline";
export { ToastVariant } from "./components/fb-toast/fb-toast";
export { ToggleSize, ToggleVariant } from "./components/fb-toggle/fb-toggle";
export { ToggleGroupOrientation, ToggleGroupSize, ToggleGroupType, ToggleGroupVariant } from "./components/fb-toggle-group/fb-toggle-group";
export namespace Components {
    interface FbAlert {
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default 'info'
         */
        "variant": AlertVariant;
    }
    interface FbAvatar {
        /**
          * @default ''
         */
        "alt": string;
        /**
          * @default ''
         */
        "initials": string;
        /**
          * @default 'circle'
         */
        "shape": 'circle' | 'square';
        /**
          * @default 'default'
         */
        "size": 'xs' | 'sm' | 'default' | 'lg' | 'xl';
        /**
          * @default ''
         */
        "src": string;
        /**
          * @default 'none'
         */
        "status": 'none' | 'online' | 'offline' | 'busy';
    }
    interface FbBadge {
        /**
          * Show a dot indicator instead of text. When true, provide a label prop for screen readers — the dot conveys meaning through colour alone which is a WCAG failure without a text alternative.
          * @default false
         */
        "dot": boolean;
        /**
          * Visible label text (also used as aria-label for dot variant)
         */
        "label": string;
        /**
          * Size
          * @default 'default'
         */
        "size": BadgeSize;
        /**
          * Visual style
          * @default 'default'
         */
        "variant": BadgeVariant;
    }
    interface FbBreadcrumb {
        /**
          * @default '[]'
         */
        "items": BreadcrumbItem[] | string;
        /**
          * @default 'Breadcrumb'
         */
        "label": string;
    }
    interface FbButton {
        /**
          * Disables the button
          * @default false
         */
        "disabled": boolean;
        /**
          * Position of the icon slot relative to the label
          * @default 'none'
         */
        "iconPosition": IconPosition;
        /**
          * Accessible label — required when iconPosition="only". For buttons with visible text this is set automatically from slot content, but icon-only buttons have no visible text so this must be provided.
         */
        "label": string;
        /**
          * Full pill / circle border radius
          * @default false
         */
        "rounded": boolean;
        /**
          * Size of the button
          * @default 'default'
         */
        "size": ButtonSize;
        /**
          * HTML type attribute
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button
          * @default 'default'
         */
        "variant": ButtonVariant;
    }
    interface FbButtonGroup {
        /**
          * @default 'horizontal'
         */
        "orientation": GroupOrientation;
        "size": string;
        "variant": string;
    }
    interface FbCard {
        /**
          * @default false
         */
        "clickable": boolean;
        /**
          * @default ''
         */
        "href": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'default'
         */
        "padding": 'none' | 'sm' | 'default' | 'lg';
        /**
          * @default 'default'
         */
        "shadow": 'none' | 'sm' | 'default' | 'lg';
    }
    interface FbCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * Shows a dash/minus — used for "select all" when some items are selected
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Visible label
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": CheckboxSize;
        /**
          * @default 'default'
         */
        "state": CheckboxState;
        /**
          * Explicit value used when inside a form
          * @default 'on'
         */
        "value": string;
    }
    interface FbChip {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Shows a remove (×) button. Emits fbRemove.
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * Makes the chip selectable (toggle). Uses role="option" + aria-selected.
          * @default false
         */
        "selectable": boolean;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default 'default'
         */
        "size": 'sm' | 'default';
        /**
          * @default 'default'
         */
        "variant": 'default' | 'primary' | 'success' | 'warning' | 'danger';
    }
    interface FbDropdown {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default '[]'
         */
        "items": DropdownItem[] | string;
        /**
          * @default 'Actions'
         */
        "label": string;
        /**
          * @default 'secondary'
         */
        "variant": 'default' | 'secondary' | 'ghost';
    }
    interface FbInput {
        /**
          * Marks the field as required
          * @default false
         */
        "clearable": boolean;
        /**
          * Helper or error message shown below the input
          * @default ''
         */
        "helperText": string;
        /**
          * Visible label text — always provide this for accessibility
          * @default ''
         */
        "label": string;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder": string;
        /**
          * Left adornment text (e.g. "$")
          * @default ''
         */
        "prefixText": string;
        /**
          * Marks the field as required
          * @default false
         */
        "required": boolean;
        /**
          * Size variant
          * @default 'default'
         */
        "size": InputSize;
        /**
          * Visual and interaction state
          * @default 'default'
         */
        "state": InputState;
        /**
          * Right adornment text (e.g. ".00")
          * @default ''
         */
        "suffixText": string;
        /**
          * HTML input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Current value
          * @default ''
         */
        "value": string;
    }
    interface FbModal {
        /**
          * @default 'Cancel'
         */
        "cancelLabel": string;
        /**
          * @default true
         */
        "closeOnOverlay": boolean;
        /**
          * @default 'Confirm'
         */
        "confirmLabel": string;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default true
         */
        "showFooter": boolean;
        /**
          * @default 'default'
         */
        "size": ModalSize;
    }
    interface FbPagination {
        /**
          * @default 1
         */
        "currentPage": number;
        /**
          * @default 'Pagination'
         */
        "label": string;
        /**
          * @default 1
         */
        "totalPages": number;
    }
    interface FbPopover {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'bottom'
         */
        "placement": 'top' | 'bottom' | 'left' | 'right';
    }
    interface FbRadioGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * Group label — rendered as <legend> inside a <fieldset>
          * @default ''
         */
        "label": string;
        /**
          * @default '[]'
         */
        "options": RadioOption[] | string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'default'
         */
        "state": 'default' | 'error';
        /**
          * @default ''
         */
        "value": string;
    }
    interface FbSelect {
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default '[]'
         */
        "options": SelectOption[] | string;
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'default'
         */
        "size": SelectSize;
        /**
          * @default 'default'
         */
        "state": SelectState;
        /**
          * @default ''
         */
        "value": string;
    }
    interface FbSeparator {
        /**
          * When true the separator is purely decorative and hidden from AT.
          * @default true
         */
        "decorative": boolean;
        /**
          * Provide a label to make this separator a section divider with a title.
          * @default ''
         */
        "label": string;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    interface FbSideSheet {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'right'
         */
        "side": 'left' | 'right';
        /**
          * @default 'default'
         */
        "size": 'sm' | 'default' | 'lg';
    }
    interface FbSidebar {
        /**
          * @default ''
         */
        "activeId": string;
        /**
          * @default false
         */
        "collapsed": boolean;
        /**
          * @default '[]'
         */
        "items": SidebarItem[] | string;
        /**
          * @default 'Main navigation'
         */
        "label": string;
    }
    interface FbSkeleton {
        /**
          * Height — any CSS value
         */
        "height": string;
        /**
          * Shape of the skeleton placeholder
          * @default 'text'
         */
        "variant": SkeletonVariant;
        /**
          * Width — any CSS value e.g. "200px", "100%", "12rem"
          * @default '100%'
         */
        "width": string;
    }
    interface FbSpinner {
        /**
          * Accessible label announced to screen readers
          * @default 'Loading, please wait'
         */
        "label": string;
        /**
          * Size of the spinner
          * @default 'default'
         */
        "size": SpinnerSize;
    }
    interface FbSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * Visible label
          * @default ''
         */
        "label": string;
    }
    interface FbTabs {
        /**
          * @default ''
         */
        "activeTab": string;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default 'Page sections'
         */
        "label": string;
        /**
          * @default 'default'
         */
        "size": TabsSize;
        /**
          * @default '[]'
         */
        "tabs": TabItem[] | string;
        /**
          * @default 'underline'
         */
        "variant": TabsVariant;
    }
    interface FbTextarea {
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * Visible label — always provide for accessibility
          * @default ''
         */
        "label": string;
        /**
          * Character limit — shows counter when set
         */
        "maxLength": number;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * Number of visible text rows
          * @default 4
         */
        "rows": number;
        /**
          * @default 'default'
         */
        "size": TextareaSize;
        /**
          * @default 'default'
         */
        "state": TextareaState;
        /**
          * @default ''
         */
        "value": string;
    }
    interface FbTimeline {
        /**
          * @default '[]'
         */
        "items": TimelineItem[] | string;
        /**
          * @default 'Timeline'
         */
        "label": string;
        /**
          * @default 'vertical'
         */
        "orientation": 'vertical' | 'horizontal';
    }
    interface FbToast {
        /**
          * Auto-dismiss delay in ms. 0 = no auto-dismiss. Minimum recommended: 5000
          * @default 6000
         */
        "duration": number;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default 'info'
         */
        "variant": ToastVariant;
        /**
          * @default false
         */
        "visible": boolean;
    }
    interface FbToggle {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * aria-label — required for icon-only toggles
         */
        "label": string;
        /**
          * @default false
         */
        "pressed": boolean;
        /**
          * @default 'default'
         */
        "size": ToggleSize;
        /**
          * @default 'default'
         */
        "variant": ToggleVariant;
    }
    interface FbToggleGroup {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * JSON array of { value, label?, icon?, disabled? }
          * @default '[]'
         */
        "items": string;
        /**
          * @default 'Toggle group'
         */
        "label": string;
        /**
          * @default 'horizontal'
         */
        "orientation": ToggleGroupOrientation;
        /**
          * @default 'default'
         */
        "size": ToggleGroupSize;
        /**
          * @default 'single'
         */
        "type": ToggleGroupType;
        /**
          * Current selection — string for single, JSON array for multiple
          * @default ''
         */
        "value": string;
        /**
          * @default 'default'
         */
        "variant": ToggleGroupVariant;
    }
    interface FbTooltip {
        /**
          * @default ''
         */
        "content": string;
        /**
          * @default 'top'
         */
        "placement": 'top' | 'bottom' | 'left' | 'right';
    }
}
export interface FbAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbAlertElement;
}
export interface FbButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbButtonElement;
}
export interface FbCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbCardElement;
}
export interface FbCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbCheckboxElement;
}
export interface FbChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbChipElement;
}
export interface FbDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbDropdownElement;
}
export interface FbInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbInputElement;
}
export interface FbModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbModalElement;
}
export interface FbPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbPaginationElement;
}
export interface FbPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbPopoverElement;
}
export interface FbRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbRadioGroupElement;
}
export interface FbSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbSelectElement;
}
export interface FbSideSheetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbSideSheetElement;
}
export interface FbSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbSidebarElement;
}
export interface FbSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbSwitchElement;
}
export interface FbTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbTabsElement;
}
export interface FbTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbTextareaElement;
}
export interface FbToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbToastElement;
}
export interface FbToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbToggleElement;
}
export interface FbToggleGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFbToggleGroupElement;
}
declare global {
    interface HTMLFbAlertElementEventMap {
        "fbDismiss": void;
    }
    interface HTMLFbAlertElement extends Components.FbAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbAlertElementEventMap>(type: K, listener: (this: HTMLFbAlertElement, ev: FbAlertCustomEvent<HTMLFbAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbAlertElementEventMap>(type: K, listener: (this: HTMLFbAlertElement, ev: FbAlertCustomEvent<HTMLFbAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbAlertElement: {
        prototype: HTMLFbAlertElement;
        new (): HTMLFbAlertElement;
    };
    interface HTMLFbAvatarElement extends Components.FbAvatar, HTMLStencilElement {
    }
    var HTMLFbAvatarElement: {
        prototype: HTMLFbAvatarElement;
        new (): HTMLFbAvatarElement;
    };
    interface HTMLFbBadgeElement extends Components.FbBadge, HTMLStencilElement {
    }
    var HTMLFbBadgeElement: {
        prototype: HTMLFbBadgeElement;
        new (): HTMLFbBadgeElement;
    };
    interface HTMLFbBreadcrumbElement extends Components.FbBreadcrumb, HTMLStencilElement {
    }
    var HTMLFbBreadcrumbElement: {
        prototype: HTMLFbBreadcrumbElement;
        new (): HTMLFbBreadcrumbElement;
    };
    interface HTMLFbButtonElementEventMap {
        "fbClick": void;
    }
    interface HTMLFbButtonElement extends Components.FbButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbButtonElementEventMap>(type: K, listener: (this: HTMLFbButtonElement, ev: FbButtonCustomEvent<HTMLFbButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbButtonElementEventMap>(type: K, listener: (this: HTMLFbButtonElement, ev: FbButtonCustomEvent<HTMLFbButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbButtonElement: {
        prototype: HTMLFbButtonElement;
        new (): HTMLFbButtonElement;
    };
    interface HTMLFbButtonGroupElement extends Components.FbButtonGroup, HTMLStencilElement {
    }
    var HTMLFbButtonGroupElement: {
        prototype: HTMLFbButtonGroupElement;
        new (): HTMLFbButtonGroupElement;
    };
    interface HTMLFbCardElementEventMap {
        "fbCardClick": void;
    }
    interface HTMLFbCardElement extends Components.FbCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbCardElementEventMap>(type: K, listener: (this: HTMLFbCardElement, ev: FbCardCustomEvent<HTMLFbCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbCardElementEventMap>(type: K, listener: (this: HTMLFbCardElement, ev: FbCardCustomEvent<HTMLFbCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbCardElement: {
        prototype: HTMLFbCardElement;
        new (): HTMLFbCardElement;
    };
    interface HTMLFbCheckboxElementEventMap {
        "fbChange": boolean;
    }
    interface HTMLFbCheckboxElement extends Components.FbCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbCheckboxElementEventMap>(type: K, listener: (this: HTMLFbCheckboxElement, ev: FbCheckboxCustomEvent<HTMLFbCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbCheckboxElementEventMap>(type: K, listener: (this: HTMLFbCheckboxElement, ev: FbCheckboxCustomEvent<HTMLFbCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbCheckboxElement: {
        prototype: HTMLFbCheckboxElement;
        new (): HTMLFbCheckboxElement;
    };
    interface HTMLFbChipElementEventMap {
        "fbSelect": boolean;
        "fbRemove": void;
    }
    interface HTMLFbChipElement extends Components.FbChip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbChipElementEventMap>(type: K, listener: (this: HTMLFbChipElement, ev: FbChipCustomEvent<HTMLFbChipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbChipElementEventMap>(type: K, listener: (this: HTMLFbChipElement, ev: FbChipCustomEvent<HTMLFbChipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbChipElement: {
        prototype: HTMLFbChipElement;
        new (): HTMLFbChipElement;
    };
    interface HTMLFbDropdownElementEventMap {
        "fbSelect": string;
    }
    interface HTMLFbDropdownElement extends Components.FbDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbDropdownElementEventMap>(type: K, listener: (this: HTMLFbDropdownElement, ev: FbDropdownCustomEvent<HTMLFbDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbDropdownElementEventMap>(type: K, listener: (this: HTMLFbDropdownElement, ev: FbDropdownCustomEvent<HTMLFbDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbDropdownElement: {
        prototype: HTMLFbDropdownElement;
        new (): HTMLFbDropdownElement;
    };
    interface HTMLFbInputElementEventMap {
        "fbChange": string;
        "fbFocus": void;
        "fbBlur": void;
    }
    interface HTMLFbInputElement extends Components.FbInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbInputElementEventMap>(type: K, listener: (this: HTMLFbInputElement, ev: FbInputCustomEvent<HTMLFbInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbInputElementEventMap>(type: K, listener: (this: HTMLFbInputElement, ev: FbInputCustomEvent<HTMLFbInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbInputElement: {
        prototype: HTMLFbInputElement;
        new (): HTMLFbInputElement;
    };
    interface HTMLFbModalElementEventMap {
        "fbClose": void;
        "fbConfirm": void;
    }
    interface HTMLFbModalElement extends Components.FbModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbModalElementEventMap>(type: K, listener: (this: HTMLFbModalElement, ev: FbModalCustomEvent<HTMLFbModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbModalElementEventMap>(type: K, listener: (this: HTMLFbModalElement, ev: FbModalCustomEvent<HTMLFbModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbModalElement: {
        prototype: HTMLFbModalElement;
        new (): HTMLFbModalElement;
    };
    interface HTMLFbPaginationElementEventMap {
        "fbPageChange": number;
    }
    interface HTMLFbPaginationElement extends Components.FbPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbPaginationElementEventMap>(type: K, listener: (this: HTMLFbPaginationElement, ev: FbPaginationCustomEvent<HTMLFbPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbPaginationElementEventMap>(type: K, listener: (this: HTMLFbPaginationElement, ev: FbPaginationCustomEvent<HTMLFbPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbPaginationElement: {
        prototype: HTMLFbPaginationElement;
        new (): HTMLFbPaginationElement;
    };
    interface HTMLFbPopoverElementEventMap {
        "fbOpen": void;
        "fbClose": void;
    }
    interface HTMLFbPopoverElement extends Components.FbPopover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbPopoverElementEventMap>(type: K, listener: (this: HTMLFbPopoverElement, ev: FbPopoverCustomEvent<HTMLFbPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbPopoverElementEventMap>(type: K, listener: (this: HTMLFbPopoverElement, ev: FbPopoverCustomEvent<HTMLFbPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbPopoverElement: {
        prototype: HTMLFbPopoverElement;
        new (): HTMLFbPopoverElement;
    };
    interface HTMLFbRadioGroupElementEventMap {
        "fbChange": string;
    }
    interface HTMLFbRadioGroupElement extends Components.FbRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbRadioGroupElementEventMap>(type: K, listener: (this: HTMLFbRadioGroupElement, ev: FbRadioGroupCustomEvent<HTMLFbRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbRadioGroupElementEventMap>(type: K, listener: (this: HTMLFbRadioGroupElement, ev: FbRadioGroupCustomEvent<HTMLFbRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbRadioGroupElement: {
        prototype: HTMLFbRadioGroupElement;
        new (): HTMLFbRadioGroupElement;
    };
    interface HTMLFbSelectElementEventMap {
        "fbChange": string;
    }
    interface HTMLFbSelectElement extends Components.FbSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbSelectElementEventMap>(type: K, listener: (this: HTMLFbSelectElement, ev: FbSelectCustomEvent<HTMLFbSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbSelectElementEventMap>(type: K, listener: (this: HTMLFbSelectElement, ev: FbSelectCustomEvent<HTMLFbSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbSelectElement: {
        prototype: HTMLFbSelectElement;
        new (): HTMLFbSelectElement;
    };
    interface HTMLFbSeparatorElement extends Components.FbSeparator, HTMLStencilElement {
    }
    var HTMLFbSeparatorElement: {
        prototype: HTMLFbSeparatorElement;
        new (): HTMLFbSeparatorElement;
    };
    interface HTMLFbSideSheetElementEventMap {
        "fbClose": void;
    }
    interface HTMLFbSideSheetElement extends Components.FbSideSheet, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbSideSheetElementEventMap>(type: K, listener: (this: HTMLFbSideSheetElement, ev: FbSideSheetCustomEvent<HTMLFbSideSheetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbSideSheetElementEventMap>(type: K, listener: (this: HTMLFbSideSheetElement, ev: FbSideSheetCustomEvent<HTMLFbSideSheetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbSideSheetElement: {
        prototype: HTMLFbSideSheetElement;
        new (): HTMLFbSideSheetElement;
    };
    interface HTMLFbSidebarElementEventMap {
        "fbNavigate": string;
    }
    interface HTMLFbSidebarElement extends Components.FbSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbSidebarElementEventMap>(type: K, listener: (this: HTMLFbSidebarElement, ev: FbSidebarCustomEvent<HTMLFbSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbSidebarElementEventMap>(type: K, listener: (this: HTMLFbSidebarElement, ev: FbSidebarCustomEvent<HTMLFbSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbSidebarElement: {
        prototype: HTMLFbSidebarElement;
        new (): HTMLFbSidebarElement;
    };
    interface HTMLFbSkeletonElement extends Components.FbSkeleton, HTMLStencilElement {
    }
    var HTMLFbSkeletonElement: {
        prototype: HTMLFbSkeletonElement;
        new (): HTMLFbSkeletonElement;
    };
    interface HTMLFbSpinnerElement extends Components.FbSpinner, HTMLStencilElement {
    }
    var HTMLFbSpinnerElement: {
        prototype: HTMLFbSpinnerElement;
        new (): HTMLFbSpinnerElement;
    };
    interface HTMLFbSwitchElementEventMap {
        "fbChange": boolean;
    }
    interface HTMLFbSwitchElement extends Components.FbSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbSwitchElementEventMap>(type: K, listener: (this: HTMLFbSwitchElement, ev: FbSwitchCustomEvent<HTMLFbSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbSwitchElementEventMap>(type: K, listener: (this: HTMLFbSwitchElement, ev: FbSwitchCustomEvent<HTMLFbSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbSwitchElement: {
        prototype: HTMLFbSwitchElement;
        new (): HTMLFbSwitchElement;
    };
    interface HTMLFbTabsElementEventMap {
        "fbTabChange": string;
    }
    interface HTMLFbTabsElement extends Components.FbTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbTabsElementEventMap>(type: K, listener: (this: HTMLFbTabsElement, ev: FbTabsCustomEvent<HTMLFbTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbTabsElementEventMap>(type: K, listener: (this: HTMLFbTabsElement, ev: FbTabsCustomEvent<HTMLFbTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbTabsElement: {
        prototype: HTMLFbTabsElement;
        new (): HTMLFbTabsElement;
    };
    interface HTMLFbTextareaElementEventMap {
        "fbChange": string;
        "fbFocus": void;
        "fbBlur": void;
    }
    interface HTMLFbTextareaElement extends Components.FbTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbTextareaElementEventMap>(type: K, listener: (this: HTMLFbTextareaElement, ev: FbTextareaCustomEvent<HTMLFbTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbTextareaElementEventMap>(type: K, listener: (this: HTMLFbTextareaElement, ev: FbTextareaCustomEvent<HTMLFbTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbTextareaElement: {
        prototype: HTMLFbTextareaElement;
        new (): HTMLFbTextareaElement;
    };
    interface HTMLFbTimelineElement extends Components.FbTimeline, HTMLStencilElement {
    }
    var HTMLFbTimelineElement: {
        prototype: HTMLFbTimelineElement;
        new (): HTMLFbTimelineElement;
    };
    interface HTMLFbToastElementEventMap {
        "fbDismiss": void;
    }
    interface HTMLFbToastElement extends Components.FbToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbToastElementEventMap>(type: K, listener: (this: HTMLFbToastElement, ev: FbToastCustomEvent<HTMLFbToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbToastElementEventMap>(type: K, listener: (this: HTMLFbToastElement, ev: FbToastCustomEvent<HTMLFbToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbToastElement: {
        prototype: HTMLFbToastElement;
        new (): HTMLFbToastElement;
    };
    interface HTMLFbToggleElementEventMap {
        "fbPressedChange": boolean;
    }
    interface HTMLFbToggleElement extends Components.FbToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbToggleElementEventMap>(type: K, listener: (this: HTMLFbToggleElement, ev: FbToggleCustomEvent<HTMLFbToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbToggleElementEventMap>(type: K, listener: (this: HTMLFbToggleElement, ev: FbToggleCustomEvent<HTMLFbToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbToggleElement: {
        prototype: HTMLFbToggleElement;
        new (): HTMLFbToggleElement;
    };
    interface HTMLFbToggleGroupElementEventMap {
        "fbChange": string | string[];
    }
    interface HTMLFbToggleGroupElement extends Components.FbToggleGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFbToggleGroupElementEventMap>(type: K, listener: (this: HTMLFbToggleGroupElement, ev: FbToggleGroupCustomEvent<HTMLFbToggleGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFbToggleGroupElementEventMap>(type: K, listener: (this: HTMLFbToggleGroupElement, ev: FbToggleGroupCustomEvent<HTMLFbToggleGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFbToggleGroupElement: {
        prototype: HTMLFbToggleGroupElement;
        new (): HTMLFbToggleGroupElement;
    };
    interface HTMLFbTooltipElement extends Components.FbTooltip, HTMLStencilElement {
    }
    var HTMLFbTooltipElement: {
        prototype: HTMLFbTooltipElement;
        new (): HTMLFbTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "fb-alert": HTMLFbAlertElement;
        "fb-avatar": HTMLFbAvatarElement;
        "fb-badge": HTMLFbBadgeElement;
        "fb-breadcrumb": HTMLFbBreadcrumbElement;
        "fb-button": HTMLFbButtonElement;
        "fb-button-group": HTMLFbButtonGroupElement;
        "fb-card": HTMLFbCardElement;
        "fb-checkbox": HTMLFbCheckboxElement;
        "fb-chip": HTMLFbChipElement;
        "fb-dropdown": HTMLFbDropdownElement;
        "fb-input": HTMLFbInputElement;
        "fb-modal": HTMLFbModalElement;
        "fb-pagination": HTMLFbPaginationElement;
        "fb-popover": HTMLFbPopoverElement;
        "fb-radio-group": HTMLFbRadioGroupElement;
        "fb-select": HTMLFbSelectElement;
        "fb-separator": HTMLFbSeparatorElement;
        "fb-side-sheet": HTMLFbSideSheetElement;
        "fb-sidebar": HTMLFbSidebarElement;
        "fb-skeleton": HTMLFbSkeletonElement;
        "fb-spinner": HTMLFbSpinnerElement;
        "fb-switch": HTMLFbSwitchElement;
        "fb-tabs": HTMLFbTabsElement;
        "fb-textarea": HTMLFbTextareaElement;
        "fb-timeline": HTMLFbTimelineElement;
        "fb-toast": HTMLFbToastElement;
        "fb-toggle": HTMLFbToggleElement;
        "fb-toggle-group": HTMLFbToggleGroupElement;
        "fb-tooltip": HTMLFbTooltipElement;
    }
}
declare namespace LocalJSX {
    interface FbAlert {
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        "onFbDismiss"?: (event: FbAlertCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: AlertVariant;
    }
    interface FbAvatar {
        /**
          * @default ''
         */
        "alt"?: string;
        /**
          * @default ''
         */
        "initials"?: string;
        /**
          * @default 'circle'
         */
        "shape"?: 'circle' | 'square';
        /**
          * @default 'default'
         */
        "size"?: 'xs' | 'sm' | 'default' | 'lg' | 'xl';
        /**
          * @default ''
         */
        "src"?: string;
        /**
          * @default 'none'
         */
        "status"?: 'none' | 'online' | 'offline' | 'busy';
    }
    interface FbBadge {
        /**
          * Show a dot indicator instead of text. When true, provide a label prop for screen readers — the dot conveys meaning through colour alone which is a WCAG failure without a text alternative.
          * @default false
         */
        "dot"?: boolean;
        /**
          * Visible label text (also used as aria-label for dot variant)
         */
        "label"?: string;
        /**
          * Size
          * @default 'default'
         */
        "size"?: BadgeSize;
        /**
          * Visual style
          * @default 'default'
         */
        "variant"?: BadgeVariant;
    }
    interface FbBreadcrumb {
        /**
          * @default '[]'
         */
        "items"?: BreadcrumbItem[] | string;
        /**
          * @default 'Breadcrumb'
         */
        "label"?: string;
    }
    interface FbButton {
        /**
          * Disables the button
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Position of the icon slot relative to the label
          * @default 'none'
         */
        "iconPosition"?: IconPosition;
        /**
          * Accessible label — required when iconPosition="only". For buttons with visible text this is set automatically from slot content, but icon-only buttons have no visible text so this must be provided.
         */
        "label"?: string;
        /**
          * Fired when the button is clicked (not fired when disabled)
         */
        "onFbClick"?: (event: FbButtonCustomEvent<void>) => void;
        /**
          * Full pill / circle border radius
          * @default false
         */
        "rounded"?: boolean;
        /**
          * Size of the button
          * @default 'default'
         */
        "size"?: ButtonSize;
        /**
          * HTML type attribute
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button
          * @default 'default'
         */
        "variant"?: ButtonVariant;
    }
    interface FbButtonGroup {
        /**
          * @default 'horizontal'
         */
        "orientation"?: GroupOrientation;
        "size"?: string;
        "variant"?: string;
    }
    interface FbCard {
        /**
          * @default false
         */
        "clickable"?: boolean;
        /**
          * @default ''
         */
        "href"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        "onFbCardClick"?: (event: FbCardCustomEvent<void>) => void;
        /**
          * @default 'default'
         */
        "padding"?: 'none' | 'sm' | 'default' | 'lg';
        /**
          * @default 'default'
         */
        "shadow"?: 'none' | 'sm' | 'default' | 'lg';
    }
    interface FbCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * Shows a dash/minus — used for "select all" when some items are selected
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Visible label
          * @default ''
         */
        "label"?: string;
        "onFbChange"?: (event: FbCheckboxCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: CheckboxSize;
        /**
          * @default 'default'
         */
        "state"?: CheckboxState;
        /**
          * Explicit value used when inside a form
          * @default 'on'
         */
        "value"?: string;
    }
    interface FbChip {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Shows a remove (×) button. Emits fbRemove.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onFbRemove"?: (event: FbChipCustomEvent<void>) => void;
        "onFbSelect"?: (event: FbChipCustomEvent<boolean>) => void;
        /**
          * Makes the chip selectable (toggle). Uses role="option" + aria-selected.
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default 'default'
         */
        "size"?: 'sm' | 'default';
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'primary' | 'success' | 'warning' | 'danger';
    }
    interface FbDropdown {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default '[]'
         */
        "items"?: DropdownItem[] | string;
        /**
          * @default 'Actions'
         */
        "label"?: string;
        "onFbSelect"?: (event: FbDropdownCustomEvent<string>) => void;
        /**
          * @default 'secondary'
         */
        "variant"?: 'default' | 'secondary' | 'ghost';
    }
    interface FbInput {
        /**
          * Marks the field as required
          * @default false
         */
        "clearable"?: boolean;
        /**
          * Helper or error message shown below the input
          * @default ''
         */
        "helperText"?: string;
        /**
          * Visible label text — always provide this for accessibility
          * @default ''
         */
        "label"?: string;
        /**
          * Fired when the input loses focus
         */
        "onFbBlur"?: (event: FbInputCustomEvent<void>) => void;
        /**
          * Fired when the value changes
         */
        "onFbChange"?: (event: FbInputCustomEvent<string>) => void;
        /**
          * Fired when the input receives focus
         */
        "onFbFocus"?: (event: FbInputCustomEvent<void>) => void;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Left adornment text (e.g. "$")
          * @default ''
         */
        "prefixText"?: string;
        /**
          * Marks the field as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Size variant
          * @default 'default'
         */
        "size"?: InputSize;
        /**
          * Visual and interaction state
          * @default 'default'
         */
        "state"?: InputState;
        /**
          * Right adornment text (e.g. ".00")
          * @default ''
         */
        "suffixText"?: string;
        /**
          * HTML input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Current value
          * @default ''
         */
        "value"?: string;
    }
    interface FbModal {
        /**
          * @default 'Cancel'
         */
        "cancelLabel"?: string;
        /**
          * @default true
         */
        "closeOnOverlay"?: boolean;
        /**
          * @default 'Confirm'
         */
        "confirmLabel"?: string;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default ''
         */
        "heading"?: string;
        "onFbClose"?: (event: FbModalCustomEvent<void>) => void;
        "onFbConfirm"?: (event: FbModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default true
         */
        "showFooter"?: boolean;
        /**
          * @default 'default'
         */
        "size"?: ModalSize;
    }
    interface FbPagination {
        /**
          * @default 1
         */
        "currentPage"?: number;
        /**
          * @default 'Pagination'
         */
        "label"?: string;
        "onFbPageChange"?: (event: FbPaginationCustomEvent<number>) => void;
        /**
          * @default 1
         */
        "totalPages"?: number;
    }
    interface FbPopover {
        /**
          * @default ''
         */
        "heading"?: string;
        "onFbClose"?: (event: FbPopoverCustomEvent<void>) => void;
        "onFbOpen"?: (event: FbPopoverCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'bottom'
         */
        "placement"?: 'top' | 'bottom' | 'left' | 'right';
    }
    interface FbRadioGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * Group label — rendered as <legend> inside a <fieldset>
          * @default ''
         */
        "label"?: string;
        "onFbChange"?: (event: FbRadioGroupCustomEvent<string>) => void;
        /**
          * @default '[]'
         */
        "options"?: RadioOption[] | string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'default'
         */
        "state"?: 'default' | 'error';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface FbSelect {
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        "onFbChange"?: (event: FbSelectCustomEvent<string>) => void;
        /**
          * @default '[]'
         */
        "options"?: SelectOption[] | string;
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'default'
         */
        "size"?: SelectSize;
        /**
          * @default 'default'
         */
        "state"?: SelectState;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface FbSeparator {
        /**
          * When true the separator is purely decorative and hidden from AT.
          * @default true
         */
        "decorative"?: boolean;
        /**
          * Provide a label to make this separator a section divider with a title.
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface FbSideSheet {
        /**
          * @default ''
         */
        "heading"?: string;
        "onFbClose"?: (event: FbSideSheetCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'right'
         */
        "side"?: 'left' | 'right';
        /**
          * @default 'default'
         */
        "size"?: 'sm' | 'default' | 'lg';
    }
    interface FbSidebar {
        /**
          * @default ''
         */
        "activeId"?: string;
        /**
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * @default '[]'
         */
        "items"?: SidebarItem[] | string;
        /**
          * @default 'Main navigation'
         */
        "label"?: string;
        "onFbNavigate"?: (event: FbSidebarCustomEvent<string>) => void;
    }
    interface FbSkeleton {
        /**
          * Height — any CSS value
         */
        "height"?: string;
        /**
          * Shape of the skeleton placeholder
          * @default 'text'
         */
        "variant"?: SkeletonVariant;
        /**
          * Width — any CSS value e.g. "200px", "100%", "12rem"
          * @default '100%'
         */
        "width"?: string;
    }
    interface FbSpinner {
        /**
          * Accessible label announced to screen readers
          * @default 'Loading, please wait'
         */
        "label"?: string;
        /**
          * Size of the spinner
          * @default 'default'
         */
        "size"?: SpinnerSize;
    }
    interface FbSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * Visible label
          * @default ''
         */
        "label"?: string;
        "onFbChange"?: (event: FbSwitchCustomEvent<boolean>) => void;
    }
    interface FbTabs {
        /**
          * @default ''
         */
        "activeTab"?: string;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default 'Page sections'
         */
        "label"?: string;
        "onFbTabChange"?: (event: FbTabsCustomEvent<string>) => void;
        /**
          * @default 'default'
         */
        "size"?: TabsSize;
        /**
          * @default '[]'
         */
        "tabs"?: TabItem[] | string;
        /**
          * @default 'underline'
         */
        "variant"?: TabsVariant;
    }
    interface FbTextarea {
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * Visible label — always provide for accessibility
          * @default ''
         */
        "label"?: string;
        /**
          * Character limit — shows counter when set
         */
        "maxLength"?: number;
        "onFbBlur"?: (event: FbTextareaCustomEvent<void>) => void;
        "onFbChange"?: (event: FbTextareaCustomEvent<string>) => void;
        "onFbFocus"?: (event: FbTextareaCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * Number of visible text rows
          * @default 4
         */
        "rows"?: number;
        /**
          * @default 'default'
         */
        "size"?: TextareaSize;
        /**
          * @default 'default'
         */
        "state"?: TextareaState;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface FbTimeline {
        /**
          * @default '[]'
         */
        "items"?: TimelineItem[] | string;
        /**
          * @default 'Timeline'
         */
        "label"?: string;
        /**
          * @default 'vertical'
         */
        "orientation"?: 'vertical' | 'horizontal';
    }
    interface FbToast {
        /**
          * Auto-dismiss delay in ms. 0 = no auto-dismiss. Minimum recommended: 5000
          * @default 6000
         */
        "duration"?: number;
        /**
          * @default ''
         */
        "message"?: string;
        "onFbDismiss"?: (event: FbToastCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: ToastVariant;
        /**
          * @default false
         */
        "visible"?: boolean;
    }
    interface FbToggle {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * aria-label — required for icon-only toggles
         */
        "label"?: string;
        "onFbPressedChange"?: (event: FbToggleCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "pressed"?: boolean;
        /**
          * @default 'default'
         */
        "size"?: ToggleSize;
        /**
          * @default 'default'
         */
        "variant"?: ToggleVariant;
    }
    interface FbToggleGroup {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * JSON array of { value, label?, icon?, disabled? }
          * @default '[]'
         */
        "items"?: string;
        /**
          * @default 'Toggle group'
         */
        "label"?: string;
        "onFbChange"?: (event: FbToggleGroupCustomEvent<string | string[]>) => void;
        /**
          * @default 'horizontal'
         */
        "orientation"?: ToggleGroupOrientation;
        /**
          * @default 'default'
         */
        "size"?: ToggleGroupSize;
        /**
          * @default 'single'
         */
        "type"?: ToggleGroupType;
        /**
          * Current selection — string for single, JSON array for multiple
          * @default ''
         */
        "value"?: string;
        /**
          * @default 'default'
         */
        "variant"?: ToggleGroupVariant;
    }
    interface FbTooltip {
        /**
          * @default ''
         */
        "content"?: string;
        /**
          * @default 'top'
         */
        "placement"?: 'top' | 'bottom' | 'left' | 'right';
    }

    interface FbAlertAttributes {
        "variant": AlertVariant;
        "heading": string;
        "description": string;
        "dismissible": boolean;
    }
    interface FbAvatarAttributes {
        "src": string;
        "alt": string;
        "initials": string;
        "size": 'xs' | 'sm' | 'default' | 'lg' | 'xl';
        "shape": 'circle' | 'square';
        "status": 'none' | 'online' | 'offline' | 'busy';
    }
    interface FbBadgeAttributes {
        "variant": BadgeVariant;
        "size": BadgeSize;
        "dot": boolean;
        "label": string;
    }
    interface FbBreadcrumbAttributes {
        "items": BreadcrumbItem[] | string;
        "label": string;
    }
    interface FbButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "iconPosition": IconPosition;
        "rounded": boolean;
        "disabled": boolean;
        "label": string;
        "type": 'button' | 'submit' | 'reset';
    }
    interface FbButtonGroupAttributes {
        "orientation": GroupOrientation;
        "variant": string;
        "size": string;
    }
    interface FbCardAttributes {
        "href": string;
        "clickable": boolean;
        "label": string;
        "padding": 'none' | 'sm' | 'default' | 'lg';
        "shadow": 'none' | 'sm' | 'default' | 'lg';
    }
    interface FbCheckboxAttributes {
        "label": string;
        "checked": boolean;
        "indeterminate": boolean;
        "state": CheckboxState;
        "size": CheckboxSize;
        "helperText": string;
        "required": boolean;
        "value": string;
    }
    interface FbChipAttributes {
        "label": string;
        "variant": 'default' | 'primary' | 'success' | 'warning' | 'danger';
        "size": 'sm' | 'default';
        "selectable": boolean;
        "selected": boolean;
        "dismissible": boolean;
        "disabled": boolean;
    }
    interface FbDropdownAttributes {
        "label": string;
        "items": DropdownItem[] | string;
        "disabled": boolean;
        "variant": 'default' | 'secondary' | 'ghost';
    }
    interface FbInputAttributes {
        "label": string;
        "type": InputType;
        "size": InputSize;
        "state": InputState;
        "placeholder": string;
        "value": string;
        "helperText": string;
        "required": boolean;
        "clearable": boolean;
        "prefixText": string;
        "suffixText": string;
    }
    interface FbModalAttributes {
        "open": boolean;
        "size": ModalSize;
        "heading": string;
        "description": string;
        "showFooter": boolean;
        "closeOnOverlay": boolean;
        "confirmLabel": string;
        "cancelLabel": string;
    }
    interface FbPaginationAttributes {
        "currentPage": number;
        "totalPages": number;
        "label": string;
    }
    interface FbPopoverAttributes {
        "heading": string;
        "placement": 'top' | 'bottom' | 'left' | 'right';
        "open": boolean;
    }
    interface FbRadioGroupAttributes {
        "label": string;
        "options": RadioOption[] | string;
        "value": string;
        "required": boolean;
        "disabled": boolean;
        "helperText": string;
        "state": 'default' | 'error';
    }
    interface FbSelectAttributes {
        "label": string;
        "options": SelectOption[] | string;
        "value": string;
        "placeholder": string;
        "state": SelectState;
        "size": SelectSize;
        "helperText": string;
        "required": boolean;
    }
    interface FbSeparatorAttributes {
        "orientation": 'horizontal' | 'vertical';
        "label": string;
        "decorative": boolean;
    }
    interface FbSideSheetAttributes {
        "open": boolean;
        "heading": string;
        "side": 'left' | 'right';
        "size": 'sm' | 'default' | 'lg';
    }
    interface FbSidebarAttributes {
        "items": SidebarItem[] | string;
        "label": string;
        "activeId": string;
        "collapsed": boolean;
    }
    interface FbSkeletonAttributes {
        "variant": SkeletonVariant;
        "width": string;
        "height": string;
    }
    interface FbSpinnerAttributes {
        "size": SpinnerSize;
        "label": string;
    }
    interface FbSwitchAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
        "helperText": string;
    }
    interface FbTabsAttributes {
        "tabs": TabItem[] | string;
        "activeTab": string;
        "variant": TabsVariant;
        "size": TabsSize;
        "fullWidth": boolean;
        "label": string;
    }
    interface FbTextareaAttributes {
        "label": string;
        "size": TextareaSize;
        "state": TextareaState;
        "placeholder": string;
        "value": string;
        "helperText": string;
        "required": boolean;
        "rows": number;
        "maxLength": number;
    }
    interface FbTimelineAttributes {
        "items": TimelineItem[] | string;
        "label": string;
        "orientation": 'vertical' | 'horizontal';
    }
    interface FbToastAttributes {
        "variant": ToastVariant;
        "message": string;
        "visible": boolean;
        "duration": number;
    }
    interface FbToggleAttributes {
        "variant": ToggleVariant;
        "size": ToggleSize;
        "pressed": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface FbToggleGroupAttributes {
        "type": ToggleGroupType;
        "variant": ToggleGroupVariant;
        "size": ToggleGroupSize;
        "orientation": ToggleGroupOrientation;
        "disabled": boolean;
        "label": string;
        "items": string;
        "value": string;
    }
    interface FbTooltipAttributes {
        "content": string;
        "placement": 'top' | 'bottom' | 'left' | 'right';
    }

    interface IntrinsicElements {
        "fb-alert": Omit<FbAlert, keyof FbAlertAttributes> & { [K in keyof FbAlert & keyof FbAlertAttributes]?: FbAlert[K] } & { [K in keyof FbAlert & keyof FbAlertAttributes as `attr:${K}`]?: FbAlertAttributes[K] } & { [K in keyof FbAlert & keyof FbAlertAttributes as `prop:${K}`]?: FbAlert[K] };
        "fb-avatar": Omit<FbAvatar, keyof FbAvatarAttributes> & { [K in keyof FbAvatar & keyof FbAvatarAttributes]?: FbAvatar[K] } & { [K in keyof FbAvatar & keyof FbAvatarAttributes as `attr:${K}`]?: FbAvatarAttributes[K] } & { [K in keyof FbAvatar & keyof FbAvatarAttributes as `prop:${K}`]?: FbAvatar[K] };
        "fb-badge": Omit<FbBadge, keyof FbBadgeAttributes> & { [K in keyof FbBadge & keyof FbBadgeAttributes]?: FbBadge[K] } & { [K in keyof FbBadge & keyof FbBadgeAttributes as `attr:${K}`]?: FbBadgeAttributes[K] } & { [K in keyof FbBadge & keyof FbBadgeAttributes as `prop:${K}`]?: FbBadge[K] };
        "fb-breadcrumb": Omit<FbBreadcrumb, keyof FbBreadcrumbAttributes> & { [K in keyof FbBreadcrumb & keyof FbBreadcrumbAttributes]?: FbBreadcrumb[K] } & { [K in keyof FbBreadcrumb & keyof FbBreadcrumbAttributes as `attr:${K}`]?: FbBreadcrumbAttributes[K] } & { [K in keyof FbBreadcrumb & keyof FbBreadcrumbAttributes as `prop:${K}`]?: FbBreadcrumb[K] };
        "fb-button": Omit<FbButton, keyof FbButtonAttributes> & { [K in keyof FbButton & keyof FbButtonAttributes]?: FbButton[K] } & { [K in keyof FbButton & keyof FbButtonAttributes as `attr:${K}`]?: FbButtonAttributes[K] } & { [K in keyof FbButton & keyof FbButtonAttributes as `prop:${K}`]?: FbButton[K] };
        "fb-button-group": Omit<FbButtonGroup, keyof FbButtonGroupAttributes> & { [K in keyof FbButtonGroup & keyof FbButtonGroupAttributes]?: FbButtonGroup[K] } & { [K in keyof FbButtonGroup & keyof FbButtonGroupAttributes as `attr:${K}`]?: FbButtonGroupAttributes[K] } & { [K in keyof FbButtonGroup & keyof FbButtonGroupAttributes as `prop:${K}`]?: FbButtonGroup[K] };
        "fb-card": Omit<FbCard, keyof FbCardAttributes> & { [K in keyof FbCard & keyof FbCardAttributes]?: FbCard[K] } & { [K in keyof FbCard & keyof FbCardAttributes as `attr:${K}`]?: FbCardAttributes[K] } & { [K in keyof FbCard & keyof FbCardAttributes as `prop:${K}`]?: FbCard[K] };
        "fb-checkbox": Omit<FbCheckbox, keyof FbCheckboxAttributes> & { [K in keyof FbCheckbox & keyof FbCheckboxAttributes]?: FbCheckbox[K] } & { [K in keyof FbCheckbox & keyof FbCheckboxAttributes as `attr:${K}`]?: FbCheckboxAttributes[K] } & { [K in keyof FbCheckbox & keyof FbCheckboxAttributes as `prop:${K}`]?: FbCheckbox[K] };
        "fb-chip": Omit<FbChip, keyof FbChipAttributes> & { [K in keyof FbChip & keyof FbChipAttributes]?: FbChip[K] } & { [K in keyof FbChip & keyof FbChipAttributes as `attr:${K}`]?: FbChipAttributes[K] } & { [K in keyof FbChip & keyof FbChipAttributes as `prop:${K}`]?: FbChip[K] };
        "fb-dropdown": Omit<FbDropdown, keyof FbDropdownAttributes> & { [K in keyof FbDropdown & keyof FbDropdownAttributes]?: FbDropdown[K] } & { [K in keyof FbDropdown & keyof FbDropdownAttributes as `attr:${K}`]?: FbDropdownAttributes[K] } & { [K in keyof FbDropdown & keyof FbDropdownAttributes as `prop:${K}`]?: FbDropdown[K] };
        "fb-input": Omit<FbInput, keyof FbInputAttributes> & { [K in keyof FbInput & keyof FbInputAttributes]?: FbInput[K] } & { [K in keyof FbInput & keyof FbInputAttributes as `attr:${K}`]?: FbInputAttributes[K] } & { [K in keyof FbInput & keyof FbInputAttributes as `prop:${K}`]?: FbInput[K] };
        "fb-modal": Omit<FbModal, keyof FbModalAttributes> & { [K in keyof FbModal & keyof FbModalAttributes]?: FbModal[K] } & { [K in keyof FbModal & keyof FbModalAttributes as `attr:${K}`]?: FbModalAttributes[K] } & { [K in keyof FbModal & keyof FbModalAttributes as `prop:${K}`]?: FbModal[K] };
        "fb-pagination": Omit<FbPagination, keyof FbPaginationAttributes> & { [K in keyof FbPagination & keyof FbPaginationAttributes]?: FbPagination[K] } & { [K in keyof FbPagination & keyof FbPaginationAttributes as `attr:${K}`]?: FbPaginationAttributes[K] } & { [K in keyof FbPagination & keyof FbPaginationAttributes as `prop:${K}`]?: FbPagination[K] };
        "fb-popover": Omit<FbPopover, keyof FbPopoverAttributes> & { [K in keyof FbPopover & keyof FbPopoverAttributes]?: FbPopover[K] } & { [K in keyof FbPopover & keyof FbPopoverAttributes as `attr:${K}`]?: FbPopoverAttributes[K] } & { [K in keyof FbPopover & keyof FbPopoverAttributes as `prop:${K}`]?: FbPopover[K] };
        "fb-radio-group": Omit<FbRadioGroup, keyof FbRadioGroupAttributes> & { [K in keyof FbRadioGroup & keyof FbRadioGroupAttributes]?: FbRadioGroup[K] } & { [K in keyof FbRadioGroup & keyof FbRadioGroupAttributes as `attr:${K}`]?: FbRadioGroupAttributes[K] } & { [K in keyof FbRadioGroup & keyof FbRadioGroupAttributes as `prop:${K}`]?: FbRadioGroup[K] };
        "fb-select": Omit<FbSelect, keyof FbSelectAttributes> & { [K in keyof FbSelect & keyof FbSelectAttributes]?: FbSelect[K] } & { [K in keyof FbSelect & keyof FbSelectAttributes as `attr:${K}`]?: FbSelectAttributes[K] } & { [K in keyof FbSelect & keyof FbSelectAttributes as `prop:${K}`]?: FbSelect[K] };
        "fb-separator": Omit<FbSeparator, keyof FbSeparatorAttributes> & { [K in keyof FbSeparator & keyof FbSeparatorAttributes]?: FbSeparator[K] } & { [K in keyof FbSeparator & keyof FbSeparatorAttributes as `attr:${K}`]?: FbSeparatorAttributes[K] } & { [K in keyof FbSeparator & keyof FbSeparatorAttributes as `prop:${K}`]?: FbSeparator[K] };
        "fb-side-sheet": Omit<FbSideSheet, keyof FbSideSheetAttributes> & { [K in keyof FbSideSheet & keyof FbSideSheetAttributes]?: FbSideSheet[K] } & { [K in keyof FbSideSheet & keyof FbSideSheetAttributes as `attr:${K}`]?: FbSideSheetAttributes[K] } & { [K in keyof FbSideSheet & keyof FbSideSheetAttributes as `prop:${K}`]?: FbSideSheet[K] };
        "fb-sidebar": Omit<FbSidebar, keyof FbSidebarAttributes> & { [K in keyof FbSidebar & keyof FbSidebarAttributes]?: FbSidebar[K] } & { [K in keyof FbSidebar & keyof FbSidebarAttributes as `attr:${K}`]?: FbSidebarAttributes[K] } & { [K in keyof FbSidebar & keyof FbSidebarAttributes as `prop:${K}`]?: FbSidebar[K] };
        "fb-skeleton": Omit<FbSkeleton, keyof FbSkeletonAttributes> & { [K in keyof FbSkeleton & keyof FbSkeletonAttributes]?: FbSkeleton[K] } & { [K in keyof FbSkeleton & keyof FbSkeletonAttributes as `attr:${K}`]?: FbSkeletonAttributes[K] } & { [K in keyof FbSkeleton & keyof FbSkeletonAttributes as `prop:${K}`]?: FbSkeleton[K] };
        "fb-spinner": Omit<FbSpinner, keyof FbSpinnerAttributes> & { [K in keyof FbSpinner & keyof FbSpinnerAttributes]?: FbSpinner[K] } & { [K in keyof FbSpinner & keyof FbSpinnerAttributes as `attr:${K}`]?: FbSpinnerAttributes[K] } & { [K in keyof FbSpinner & keyof FbSpinnerAttributes as `prop:${K}`]?: FbSpinner[K] };
        "fb-switch": Omit<FbSwitch, keyof FbSwitchAttributes> & { [K in keyof FbSwitch & keyof FbSwitchAttributes]?: FbSwitch[K] } & { [K in keyof FbSwitch & keyof FbSwitchAttributes as `attr:${K}`]?: FbSwitchAttributes[K] } & { [K in keyof FbSwitch & keyof FbSwitchAttributes as `prop:${K}`]?: FbSwitch[K] };
        "fb-tabs": Omit<FbTabs, keyof FbTabsAttributes> & { [K in keyof FbTabs & keyof FbTabsAttributes]?: FbTabs[K] } & { [K in keyof FbTabs & keyof FbTabsAttributes as `attr:${K}`]?: FbTabsAttributes[K] } & { [K in keyof FbTabs & keyof FbTabsAttributes as `prop:${K}`]?: FbTabs[K] };
        "fb-textarea": Omit<FbTextarea, keyof FbTextareaAttributes> & { [K in keyof FbTextarea & keyof FbTextareaAttributes]?: FbTextarea[K] } & { [K in keyof FbTextarea & keyof FbTextareaAttributes as `attr:${K}`]?: FbTextareaAttributes[K] } & { [K in keyof FbTextarea & keyof FbTextareaAttributes as `prop:${K}`]?: FbTextarea[K] };
        "fb-timeline": Omit<FbTimeline, keyof FbTimelineAttributes> & { [K in keyof FbTimeline & keyof FbTimelineAttributes]?: FbTimeline[K] } & { [K in keyof FbTimeline & keyof FbTimelineAttributes as `attr:${K}`]?: FbTimelineAttributes[K] } & { [K in keyof FbTimeline & keyof FbTimelineAttributes as `prop:${K}`]?: FbTimeline[K] };
        "fb-toast": Omit<FbToast, keyof FbToastAttributes> & { [K in keyof FbToast & keyof FbToastAttributes]?: FbToast[K] } & { [K in keyof FbToast & keyof FbToastAttributes as `attr:${K}`]?: FbToastAttributes[K] } & { [K in keyof FbToast & keyof FbToastAttributes as `prop:${K}`]?: FbToast[K] };
        "fb-toggle": Omit<FbToggle, keyof FbToggleAttributes> & { [K in keyof FbToggle & keyof FbToggleAttributes]?: FbToggle[K] } & { [K in keyof FbToggle & keyof FbToggleAttributes as `attr:${K}`]?: FbToggleAttributes[K] } & { [K in keyof FbToggle & keyof FbToggleAttributes as `prop:${K}`]?: FbToggle[K] };
        "fb-toggle-group": Omit<FbToggleGroup, keyof FbToggleGroupAttributes> & { [K in keyof FbToggleGroup & keyof FbToggleGroupAttributes]?: FbToggleGroup[K] } & { [K in keyof FbToggleGroup & keyof FbToggleGroupAttributes as `attr:${K}`]?: FbToggleGroupAttributes[K] } & { [K in keyof FbToggleGroup & keyof FbToggleGroupAttributes as `prop:${K}`]?: FbToggleGroup[K] };
        "fb-tooltip": Omit<FbTooltip, keyof FbTooltipAttributes> & { [K in keyof FbTooltip & keyof FbTooltipAttributes]?: FbTooltip[K] } & { [K in keyof FbTooltip & keyof FbTooltipAttributes as `attr:${K}`]?: FbTooltipAttributes[K] } & { [K in keyof FbTooltip & keyof FbTooltipAttributes as `prop:${K}`]?: FbTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fb-alert": LocalJSX.IntrinsicElements["fb-alert"] & JSXBase.HTMLAttributes<HTMLFbAlertElement>;
            "fb-avatar": LocalJSX.IntrinsicElements["fb-avatar"] & JSXBase.HTMLAttributes<HTMLFbAvatarElement>;
            "fb-badge": LocalJSX.IntrinsicElements["fb-badge"] & JSXBase.HTMLAttributes<HTMLFbBadgeElement>;
            "fb-breadcrumb": LocalJSX.IntrinsicElements["fb-breadcrumb"] & JSXBase.HTMLAttributes<HTMLFbBreadcrumbElement>;
            "fb-button": LocalJSX.IntrinsicElements["fb-button"] & JSXBase.HTMLAttributes<HTMLFbButtonElement>;
            "fb-button-group": LocalJSX.IntrinsicElements["fb-button-group"] & JSXBase.HTMLAttributes<HTMLFbButtonGroupElement>;
            "fb-card": LocalJSX.IntrinsicElements["fb-card"] & JSXBase.HTMLAttributes<HTMLFbCardElement>;
            "fb-checkbox": LocalJSX.IntrinsicElements["fb-checkbox"] & JSXBase.HTMLAttributes<HTMLFbCheckboxElement>;
            "fb-chip": LocalJSX.IntrinsicElements["fb-chip"] & JSXBase.HTMLAttributes<HTMLFbChipElement>;
            "fb-dropdown": LocalJSX.IntrinsicElements["fb-dropdown"] & JSXBase.HTMLAttributes<HTMLFbDropdownElement>;
            "fb-input": LocalJSX.IntrinsicElements["fb-input"] & JSXBase.HTMLAttributes<HTMLFbInputElement>;
            "fb-modal": LocalJSX.IntrinsicElements["fb-modal"] & JSXBase.HTMLAttributes<HTMLFbModalElement>;
            "fb-pagination": LocalJSX.IntrinsicElements["fb-pagination"] & JSXBase.HTMLAttributes<HTMLFbPaginationElement>;
            "fb-popover": LocalJSX.IntrinsicElements["fb-popover"] & JSXBase.HTMLAttributes<HTMLFbPopoverElement>;
            "fb-radio-group": LocalJSX.IntrinsicElements["fb-radio-group"] & JSXBase.HTMLAttributes<HTMLFbRadioGroupElement>;
            "fb-select": LocalJSX.IntrinsicElements["fb-select"] & JSXBase.HTMLAttributes<HTMLFbSelectElement>;
            "fb-separator": LocalJSX.IntrinsicElements["fb-separator"] & JSXBase.HTMLAttributes<HTMLFbSeparatorElement>;
            "fb-side-sheet": LocalJSX.IntrinsicElements["fb-side-sheet"] & JSXBase.HTMLAttributes<HTMLFbSideSheetElement>;
            "fb-sidebar": LocalJSX.IntrinsicElements["fb-sidebar"] & JSXBase.HTMLAttributes<HTMLFbSidebarElement>;
            "fb-skeleton": LocalJSX.IntrinsicElements["fb-skeleton"] & JSXBase.HTMLAttributes<HTMLFbSkeletonElement>;
            "fb-spinner": LocalJSX.IntrinsicElements["fb-spinner"] & JSXBase.HTMLAttributes<HTMLFbSpinnerElement>;
            "fb-switch": LocalJSX.IntrinsicElements["fb-switch"] & JSXBase.HTMLAttributes<HTMLFbSwitchElement>;
            "fb-tabs": LocalJSX.IntrinsicElements["fb-tabs"] & JSXBase.HTMLAttributes<HTMLFbTabsElement>;
            "fb-textarea": LocalJSX.IntrinsicElements["fb-textarea"] & JSXBase.HTMLAttributes<HTMLFbTextareaElement>;
            "fb-timeline": LocalJSX.IntrinsicElements["fb-timeline"] & JSXBase.HTMLAttributes<HTMLFbTimelineElement>;
            "fb-toast": LocalJSX.IntrinsicElements["fb-toast"] & JSXBase.HTMLAttributes<HTMLFbToastElement>;
            "fb-toggle": LocalJSX.IntrinsicElements["fb-toggle"] & JSXBase.HTMLAttributes<HTMLFbToggleElement>;
            "fb-toggle-group": LocalJSX.IntrinsicElements["fb-toggle-group"] & JSXBase.HTMLAttributes<HTMLFbToggleGroupElement>;
            "fb-tooltip": LocalJSX.IntrinsicElements["fb-tooltip"] & JSXBase.HTMLAttributes<HTMLFbTooltipElement>;
        }
    }
}
